### ISSUE TITLE
Notification popups do not show enough text

### ISSUE THREAD

**Issue by Izaic** [JF002/Pinetime#117]
The notification popups are just too tiny to see enough text. In my opinion they should take up the whole screen and close after a few seconds, or require a press to confirm that you've seen the message.

**Comment by Avamander** [comment]
Will be improved by https://github.com/JF002/Pinetime/tree/notification-ui maybe available in the next release

**Comment by JF002** [comment]
If you have a dev kit with an SWD debugger, you can try this release candidate version and tell us what you think : https://github.com/JF002/Pinetime/releases/tag/0.9.0-develop

Warning : Do not try it on a sealed device!

**Comment by JF002** [comment]
The new notification UI is now available in InfiniTime 0.9.0 and is supported by gadgetbridge 0.49! I'm closing this issue.
