### ISSUE TITLE
Battery level always shows 100% or 0%

### ISSUE THREAD

**Issue by thelovebug** [JF002/Pinetime#119]
Firmware 0.8.3 running on a sealed PineTime

The battery level on the information screen (bottom left icon on the first menu) always shows 100% or 0%.  I can't tell you at what point the level changes, but it was showing 100% for at least a day before changing to 0%, and it's been at least 3 days since then.

The battery icon on the main time view seems to reflect the battery level correctly, however.

![400097000710_118170](https://user-images.githubusercontent.com/2915687/97778069-8d8a4880-1b6c-11eb-8696-ad008af750c5.jpg)

**Comment by JF002** [comment]
Thanks for your feedback! I'll have a look when I have a bit of time ;)

**Comment by IoTPanic** [comment]
+1 Same issue, battery state in the battery icon on home seems fine, however after updating from 0.7.1 to 0.8.3 broke the menu battery percentage as pictured in thelovebugs post. Hope this tad extra info helps.
