### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by SecureCodeJIT** [JF002/Pinetime#123]
Clock - multiple time zones &. world clock.  Ability to display 2 different timezones at a time.

**Comment by JF002** [comment]
Thanks for your suggestion. Would you like to provide us with a drawing showing how all these info would be displayed on the screen ?
We also have to think about a way to configure the timezones that will be displayed,...

**Comment by pfeerick** [comment]
@SecureCodeJIT Would you mind updating the issue title to reflect that it is about... i.e. `Enhancement - Clock multiple timezones and world clock`
