### ISSUE TITLE
OTA

### ISSUE THREAD

**Issue by danielkucera** [JF002/Pinetime#14]
I'd like to close and wear my watch. Would it be possible to implement some over-the-air update mechanism? To split it to a bootloader and main app?

**Comment by JF002** [comment]
I plan on implementing such kind of feature, yes.
However, it won't be an easy task. As you said, a bootloader will be necessary.
It would be a good idea to work with the community so that all Pinetime project use the same bootloader.

Any help is welcome!

**Comment by danielkucera** [comment]
It seems to be quite easy: https://devzone.nordicsemi.com/nordic/nordic-blog/b/blog/posts/getting-started-with-nordics-secure-dfu-bootloader

**Comment by JF002** [comment]
Thanks for the link!
On the chat, some people seem interested in https://mcuboot.com/

**Comment by danielkucera** [comment]
I'll hopefully test this today in the evening. What chat do you mean @JF002 ?

**Comment by JF002** [comment]
There are several chat rooms (Matrix, Discord, IRC, Telegram) that are linked together by bots. I'm on the Matrix one (https://riot.im/app/#/room/#pinetime64:matrix.org), but you can join from another IM app if you want. See the menu "Forum and Chat" on pine64.org.
