### ISSUE TITLE
SystemInfo app reports wrong battery percentage

### ISSUE THREAD

**Issue by Kozova1** [JF002/Pinetime#142]
Somewhere between 0.7.1 (I think) and 0.8.3 the SystemInfo app stopped reporting the battery percentage. it just shows 0% always. The watch face shows roughly the right amount (around 50% for me at the moment).
This is still broken on 0.9.0.

**Comment by Avamander** [comment]
Fixed in https://github.com/JF002/Pinetime/pull/125
