### ISSUE TITLE
Vibration when a notification is recieved

### ISSUE THREAD

**Issue by Jab2870** [JF002/Pinetime#177]
Hi,

Thanks everyone involved with this project.

Would it be possible to have the watch vibrate when a notification arrives?

This is perhaps related to #115. I am not sure if the vibration motor is even
working yet.

**Comment by petterhs** [comment]
This is being worked on/reviewed in #167. So soon

**Comment by JF002** [comment]
It's now merged and released in InfiniTime 0.13.0 :)
