### ISSUE TITLE
Make BLE softdevice optional

### ISSUE THREAD

**Issue by JF002** [JF002/Pinetime#3]
Detect the presence of the BLE softdevice, and disable BLE if the softdevice is not present in memory.

This will allow the firmware to work even if the softdevice hasn't been uploaded to the device memory.

**Comment by JF002** [comment]
This one doesn't seem easy, or even possible : when the MCU starts, the address of the first instructions it tries to execute correspond to an address that should be programmed by the softdevice.
If the softdevice is not flashed, there is not data in FLASH memory from 0x00000 to 0x26000, and the MCU executes garbage.

I think the only way to make the softdevice optional is to do it at compile time, but not at run time.

Any advice?

**Comment by danielkucera** [comment]
For this purpose you could perhaps create a small bootloader that will be residing at 0x0 and will jump to the main app at 0x26000 to keep the main binary compatible between SD and non-SD version

**Comment by JF002** [comment]
Good idea! I think I saw a reference to a MBR (Master Boot Record) in the NRF52-SDK. Maybe it could be useful.

**Comment by JF002** [comment]
Since 0.5.0, the softdevice has been replaced by nimBLE as BLE stack. This issue is not relevant anymore.
