### ISSUE TITLE
Firmware Version in nRF Connect

### ISSUE THREAD

**Issue by lupyuen** [JF002/Pinetime#58]
0.8.0 Release Candidate works great via DFU great job! :-) Just a minor cosmetic issue: The Firmware Revision reported by nRF Connect still shows 0.7.0 instead of 0.8.0. Thanks!

![Screenshot_20200901-103148](https://user-images.githubusercontent.com/9960133/91788556-19502900-ec3f-11ea-8272-a6f8aa8dfc95.png)

**Comment by JF002** [comment]
You're the eagle eye, @lupyuen. The version reported on BLE is hard-coded (and I forgot to update it) and it should be updated automatically when the project version is changed. Should be easy to fix!

**Comment by JF002** [comment]
Fixed in https://github.com/JF002/Pinetime/commit/1aa5b0a440de3015b5b4c88aa32d149a69bfa707.
