### ISSUE TITLE
Broken link to Gadgetbridge

### ISSUE THREAD

**Issue by hrmckay** [JF002/Pinetime#63]
The link to the Gadgetbridge version that works with InfiniTime gives a 404 error.

Hugh

**Comment by Avamander** [comment]
Just mentioning that initial support for InfiniTime firmware is already available in the latest version on F-Droid.

**Comment by hrmckay** [comment]
Thanks for the information, that was what I needed to know.

Hugh

**Comment by JF002** [comment]
I'll probably need to update the link now that the support is merged into the official release of Gadgetbridge. Thanks for reporting this dead link!

**Comment by JF002** [comment]
Fixed in 0a1bebf1b7f05fb3aa5a4705a13fd2251559c6b7.
