### ISSUE TITLE
Can I haz Hacktoberfest, please?

### ISSUE THREAD

**Issue by jotasprout** [JF002/Pinetime#89]
Based on a tutorial I followed and help from @lupyuen on issue #65 (mine, now closed), I'd like to contribute to this repo and his (and perhaps others) as I am absolutely loving learning and hacking with PineTime. I'm also passionate about Hacktoberfest so, if you're willing, could you opt in to it? If not, I still want to contribute and definitely will, but, if you're willing, here's some info:
<img width="972" alt="hackstuff" src="https://user-images.githubusercontent.com/12866150/95263819-62763880-07fc-11eb-925b-3c5b4899aa0d.png">

**Comment by lupyuen** [comment]
@JF002 What do you think?

**Comment by Avamander** [comment]
@lupyuen the topic is already applied.

**Comment by JF002** [comment]
Yes, the label is already applied on the repo. Do I need to do something else to enable hacktoberfest?

**Comment by Avamander** [comment]
You don't have to do anything else.
